### ISSUE TITLE
Version of Synapse for MAC OS Sierra

### ISSUE THREAD

**Issue by WoutClarysse** [jpbellona/Kinect-Via-Synapse#1]
Hello,

The version of synapse seems not be working on my macbook pro 2015 OS Sierra, I can't open the program. 

I really like to use this. Is there any way I can use this?

Wout

**Comment by jpbellona** [comment]
Hmmm, Synapse software is owned and operated by Ryan Challinor, which lives online here: http://synapsekinect.tumblr.com/

I built Kinect-via-Synapse to interface with his software, but it's not the only way to get working with the Kinect. One of the major hangs with Synapse is to check your hardware. Synapse seems to only work with hardware version 1414 (as posted on Ryan's site, see above link).

You may check out my SimpleK software (must be used with Processing for OS Sierra), but I understand this does require some more installation of software, including Processing and some libraries.

**Comment by WoutClarysse** [comment]
Thanks for the replay.
And I didn't know I had my kinect to be connected while starting the program. 
I ordered a usb adapter and I will try it again. 
My last question.
While connecting my kinect 1414 for the first time, do I need to install drivers or something?
Or will it just work right on? 
Thanks.

**Comment by jpbellona** [comment]
The nice thing about Synapse is that the drivers are pre-installed with the software. This is (*I think*) the reason it is hardware specific to the 1414.  For other Kinect software I've worked with, you have to install drivers.  I have not tested Synapse on OS Sierra.
